# Generated by Django 5.0.4 on 2024-08-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cemsdata',
            name='modify',
            field=models.BooleanField(default=True),
        ),
    ]
