# Generated by Django 5.0.4 on 2024-08-03 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cemsdata_modify'),
    ]

    operations = [
        migrations.AddField(
            model_name='cemsdata',
            name='dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
