# Generated by Django 5.0.4 on 2024-08-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cemsdata_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardInstruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('upper_limit', models.FloatField()),
                ('lower_limit', models.FloatField()),
                ('serial_number', models.CharField(max_length=255)),
                ('model_number', models.CharField(max_length=255)),
                ('last_cal_date', models.DateTimeField()),
                ('due_cal_date', models.DateTimeField()),
                ('calibrated_by', models.CharField(max_length=255)),
                ('picture', models.FileField(blank=True, null=True, upload_to='standar_instruments')),
            ],
        ),
        migrations.RenameField(
            model_name='calsheet',
            old_name='device_type',
            new_name='design_type',
        ),
        migrations.RenameField(
            model_name='calsheet',
            old_name='variable',
            new_name='process_type',
        ),
        migrations.RemoveField(
            model_name='calsheet',
            name='afactual',
        ),
        migrations.RemoveField(
            model_name='calsheet',
            name='afdesire',
        ),
        migrations.RemoveField(
            model_name='calsheet',
            name='aferror',
        ),
        migrations.RemoveField(
            model_name='calsheet',
            name='alactual',
        ),
        migrations.RemoveField(
            model_name='calsheet',
            name='aldesire',
        ),
        migrations.RemoveField(
            model_name='calsheet',
            name='alerror',
        ),
        migrations.RemoveField(
            model_name='calsheet',
            name='sheet_id',
        ),
        migrations.RemoveField(
            model_name='calsheet',
            name='te_man',
        ),
        migrations.RemoveField(
            model_name='calsheet',
            name='te_serial_number',
        ),
        migrations.RemoveField(
            model_name='calsheet',
            name='te_validity_period',
        ),
        migrations.AddField(
            model_name='calsheet',
            name='af_actual0',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='af_actual100',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='af_actual25',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='af_actual50',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='af_actual75',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='af_desire0',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='af_desire100',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='af_desire25',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='af_desire50',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='af_desire75',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='al_actual0',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='al_actual100',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='al_actual25',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='al_actual50',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='al_actual75',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='al_desire0',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='al_desire100',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='al_desire25',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='al_desire50',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='al_desire75',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='al_deviation',
            field=models.FloatField(default=0, verbose_name='As left error'),
        ),
        migrations.AddField(
            model_name='calsheet',
            name='by',
            field=models.CharField(default='user', max_length=225, verbose_name='By'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calsheet',
            name='standard_instrument',
            field=models.CharField(default='stdins', max_length=225, verbose_name='TE description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calsheet',
            name='deviation_type',
            field=models.CharField(default=0, max_length=225, verbose_name='None'),
        ),
        migrations.AlterField(
            model_name='calsheet',
            name='lower_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calsheet',
            name='lower_range',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calsheet',
            name='remarks',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='calsheet',
            name='upper_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calsheet',
            name='upper_range',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='media',
            field=models.FileField(upload_to='gallery'),
        ),
    ]
