# Generated by Django 5.0.4 on 2024-08-04 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_calsheet_cal_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calsheet',
            name='expiry',
        ),
    ]
