# Generated by Django 5.0.4 on 2024-08-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_calsheet_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calsheet',
            old_name='calibration_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='calsheet',
            name='deviation_type',
            field=models.CharField(default=0, max_length=225, verbose_name='Deviation type'),
        ),
        migrations.AlterField(
            model_name='calsheet',
            name='standard_instrument',
            field=models.CharField(max_length=225),
        ),
    ]
