# Generated by Django 5.0.4 on 2024-08-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_gallery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='member_id',
        ),
        migrations.AddField(
            model_name='admin',
            name='employee_id',
            field=models.IntegerField(default=1000, verbose_name='Admin employee id'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_type',
            field=models.CharField(default='admin', max_length=255),
        ),
        migrations.AlterField(
            model_name='admin',
            name='ppic',
            field=models.FileField(null=True, upload_to='admins', verbose_name='Profile picture'),
        ),
    ]
