# Generated by Django 5.0.4 on 2024-08-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_admin_member_id_admin_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='local',
        ),
    ]
