# Generated by Django 5.0.4 on 2024-08-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_admin_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='admin',
            name='ppic',
            field=models.FileField(default='/static/img/profile_small.jpg', upload_to='admins', verbose_name='Profile picture'),
        ),
    ]
