# Generated by Django 5.0.4 on 2024-08-08 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_resettokens_alter_admin_is_admin_alter_admin_ppic'),
    ]

    operations = [
        migrations.AddField(
            model_name='resettokens',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
