# Generated by Django 5.0.4 on 2024-08-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_resettokens_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettokens',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
