# Generated by Django 5.0.4 on 2024-08-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_resettokens_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manuals',
            old_name='category',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='manuals',
            name='manufacturer',
        ),
        migrations.AlterField(
            model_name='manuals',
            name='media',
            field=models.FileField(blank=True, default='normal document', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
