# Generated by Django 5.0.4 on 2024-08-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_category_manuals_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuals',
            name='by',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
    ]
