# Generated by Django 5.0.4 on 2024-08-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_manuals_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=225, verbose_name='By')),
                ('action', models.CharField(max_length=225, verbose_name='From')),
                ('type', models.CharField(default='', max_length=225, verbose_name='Type')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('read', models.BooleanField(default=False, verbose_name='Is read')),
                ('personal', models.BooleanField(default=False, verbose_name='Is personal')),
                ('color', models.CharField(default='primary', max_length=225, verbose_name='From')),
                ('tag', models.CharField(default='primary', max_length=225, verbose_name='From')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frm', models.CharField(max_length=225, verbose_name='From')),
                ('to', models.CharField(max_length=225, verbose_name='To')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Date')),
                ('read', models.BooleanField(default=False, verbose_name='Is read')),
                ('message', models.CharField(default='', max_length=225, verbose_name='Message')),
                ('tag', models.CharField(default='primary', max_length=225, verbose_name='From')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=225, verbose_name='From')),
                ('fr', models.CharField(max_length=225, verbose_name='for')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('read', models.BooleanField(default=False, verbose_name='Is read')),
                ('message', models.CharField(default='', max_length=225, verbose_name='Message')),
                ('tag', models.CharField(default='primary', max_length=225, verbose_name='From')),
            ],
        ),
    ]
