# Generated by Django 5.0.4 on 2024-08-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_activities_message_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='cemsdata',
            name='unit31_power',
            field=models.FloatField(default=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cemsdata',
            name='unit32_power',
            field=models.FloatField(default=110),
            preserve_default=False,
        ),
    ]
