# Generated by Django 5.1.1 on 2024-10-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='by',
        ),
    ]
