# Generated by Django 5.1.1 on 2024-10-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_user_todo_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(default='low', max_length=225),
        ),
    ]
