# Generated by Django 5.1.1 on 2024-10-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_todo_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('featured_picture_1', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('featured_picture_2', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('featured_picture_3', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('featured_picture_4', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('featured_picture_5', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('featured_picture_6', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('asset', models.CharField(max_length=100)),
                ('work_order_number', models.CharField(max_length=100)),
                ('permit_number', models.CharField(max_length=100)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('observations', models.TextField()),
                ('actions_implemented', models.TextField()),
                ('item_replaced', models.BooleanField(default=False)),
                ('item_replaced_code', models.TextField()),
            ],
        ),
    ]
