# Generated by Django 5.1.1 on 2024-10-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='conclusion',
            field=models.TextField(default='Device is now working perfectly'),
        ),
    ]
