# Generated by Django 5.1.1 on 2024-10-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_calsheet_af_error0_calsheet_af_error100_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuals',
            name='ext',
            field=models.CharField(default='pdf', max_length=255),
        ),
    ]
