# Generated by Django 5.1.1 on 2024-10-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_manuals_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuals',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
